### PR TITLE
threading for Bullet2

### PR DESCRIPTION
**Pull request by lunkhound**
MultiThreadedDemo uses either TBB or OpenMP (issue #126)
Also makes Dvbt rayTest threadsafe (issue #254, #258)
Discussion (here)[http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=10232]

Areas that run in parallel:
 - narrowphase (dispatchAllPairs)
 - discreteDynamicsWorld solve islands (each island is a separate task)
 - discreteDynamicsWorld predictUnconstraintMotion
 - discreteDynamicsWorld createPredictiveContacts
 - discreteDynamicsWorld integrateTransforms

There were some significant changes to how the btSimulationIslandManager works, so that islands could be dispatched in parallel to different solvers.

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for sharing your multithreading code! 
I'll give some feedback once I get the time to review it properly.

**Comment by lunkhound** [comment]
Thanks!  I welcome any feedback or questions.

**Comment by erwincoumans** [comment]
I cannot accept the patch right now, because I am focussing on Bullet 3.x and rethinking the whole API and such. I'll take a look at your patch anyway, and see what will be useful for future refactoring.
I'll leave the pull request open anyway, hopefully someone can use the patch.

**Comment by lunkhound** [comment]
I am currently working on rebasing the work in this patch to the current version of bullet. I've collapsed it from 50+ commits to about 12 or so. I'm stripping out various dead-end lines of development and failed experiments, so the resulting patch should be much easier to follow. All the changes to the bullet core are already applied, all that remains is to port the demo to the new example browser framework. When it is ready I'll create a new pull request.

**Comment by lunkhound** [comment]
Closing this in favor of the newer PR.

**Pull request closed without merging**
