### PR TITLE
Update support for buggy android NDK

### PR DESCRIPTION
**Pull request by kwasimensah**
Expand logic for when __thread is supported to work around https://github.com/android-ndk/ndk/issues/8

### CODE REVIEW

**Comment by erwincoumans** [comment]
OK, let me have a look and merge it today, Thanks!

**Comment by erwincoumans** [comment]
Mac OSX platform is affected by this change. Could you rewrite the patch, using  
```
#if defined(__ANDROID__) 
 //some new logic, 
#else 
unmodified existing logic 
#endif
```
then there is less chance it breaks other platforms.

**Comment by kwasimensah** [comment]
Ok, pushed new version. Will wait for tests to pass

**Comment by kwasimensah** [comment]
Tests have passed. I think this can be integrated now.

**Comment by erwincoumans** [comment]
Since the logic is more complex than #if defined(__ANDROID__)  #else <unmodified> #endif I'll have to manually go through the code and test if this doesn't break on any platform.

**Comment by erwincoumans** [comment]
Thanks for the pull request!

**Comment by erwincoumans** [comment]
OMG, this patch seems to be broken indeed: https://github.com/bulletphysics/bullet3/commit/8aefa7e8d05118a09d9bb3a4c49db7678391b7b5#commitcomment-25547649

So it gets reverted and I'll have to manually change the logic to not break things....

**Comment by kwasimensah** [comment]
Pull request is at https://github.com/bulletphysics/bullet3/pull/1431

**Comment by AndresTraks** [comment]
The new patch fixes it.

BT_THREADSAFE is defined when BULLET2_USE_THREAD_LOCKS is set in CMake, so you'd have to build two configurations if you want to test this. It makes sense for it to be a preprocessor macro, because otherwise, with the way multi-threading is done now, an "isThreadSafe" variable would have to be checked a lot during simulation.

As an exception, I think btQuickProf should be made thread-safe by default or at least redesigned to not use static variables, because it crashes in the case where you want to simulate completely separate worlds in separate threads, which has nothing to do with Bullet's multi-threading functionality: http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?t=5588

**Comment by erwincoumans** [comment]
Good point. btQuickProf/BT_PROFILE is used for benchmarking, and we mainly use the newer and better b3ProfileZone/B3_PROFILE instead. At some stage, I'll have to retire LinearMath and move to Bullet3Common, have to figure out when/how to avoid breaking lots of code bases.

**Pull request merged**
