### PR TITLE
add new example for btCompoundShape

### PR DESCRIPTION
**Pull request by srajangarg**
https://github.com/bulletphysics/bullet3/issues/1352

### CODE REVIEW

**Comment by srajangarg** [comment]
ping @erwincoumans

**Comment by erwincoumans** [comment]
Thanks! Could you also add the file to the premake build file (at least Bullet/examples/ExampleBrowser/premake4.lua)?

**Comment by srajangarg** [comment]
I checked the premake build files, none of them have `SimpleBox.cpp` / `SimpleBox.h` in them. If premake builds SimpleBox, then CompoundBoxes will also be built. (via maybe the *.cpp / *.h directive) However, it might be the case none of them are being built, haven't tested out the premake build system.

Re : CI, maybe you can just add additional travis jobs which build using premake?

**Comment by erwincoumans** [comment]
Ah, that's right, premake likely uses a wildcard *.cpp. 

Do you have time to add an additional travis job?
On Linux the procedure to build would be:
cd build3
./premake4_linux64 gmake
cd gmake
make -j12

On OSX , replace the command with ./premake4_osx

**Comment by srajangarg** [comment]
I'll try and look at premake builds later. Mayeb after I add the VHACD convex decomposition example.

**Pull request merged**
