### PR TITLE
The 'static' storage-class specifier is not supported in OpenCL.

### PR DESCRIPTION
**Pull request by hujiajie**
This is documented in Section 6.8 (g) in OpenCL 1.1 specification.

### CODE REVIEW

**Comment by hujiajie** [comment]
@erwincoumans Please take a look

**Comment by erwincoumans** [comment]
It looks good, but could you please rename the 'STATIC' to 'B3_STATIC'?

**Comment by hujiajie** [comment]
Done

**Comment by erwincoumans** [comment]
thanks for the report and contribution!

**Pull request merged**
