### PR TITLE
Modify pybullet renderImage to return numpy array

### PR DESCRIPTION
**Pull request by moof2k**
Improves testrender.py performance on large images an order of magnitude

@erwincoumans

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the contribution! This adds a dependency to numpy, which some
people like, others don't (on windows, many don't have numpy installed)


Could you put it behind an #ifdef, disabled by default? Then we can add the
option in the various build systems(I can take care of cmake, premake and
google3 BUILD ;)

Thanks!
Erwin

**Comment by BluePrintRandom** [comment]
How does one distribute a application, and have it automatically install
the dependencies?

Can pip do that?

(like if you turn on his option and numpy is not installed, open a prompt
that asks the user if they want python to retrieve it?)

**Comment by erwincoumans** [comment]
I re-created this pull request with your changes, with optional numpy support, works through cmake if your environment is setup ok: https://github.com/bulletphysics/bullet3/pull/780
Thanks!

**Comment by erwincoumans** [comment]
This was merged instead: https://github.com/bulletphysics/bullet3/pull/780
We could also move the contact point data (and upcoming raycast data) in numpy arrays.
Thanks for the contribution!

**Pull request closed without merging**
