### PR TITLE
Fix double to float conversion warning

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by erwincoumans** [comment]
Now compile the code using BT_USE_DOUBLE_PRECISION (that is the new default for pybullet and our usage) and you introduce a warning there...

**Comment by 1vanK** [comment]
Hm, in VS no warnings for conversion float to double

**Comment by iSLC** [comment]
I suppose if you want to got the ugly route you could do something like:
```
#ifndef BT_USE_DOUBLE_PRECISION
    #define BT_F(v) v ## f
#else
    #define BT_F(v) v
#endif
```

And then:
```
btVector3(BT_F(1.0), BT_F(0.3), BT_F(0.3))
```

**Comment by erwincoumans** [comment]
You can already do btVector3(btScalar(1),btScalar(0.3),btScalar(0.3)); 
Equally ugly and overly verbose indeed, hence the warnings are still there.

**Comment by lunkhound** [comment]
I really don't see the point of such warnings for compile-time numerical constants. In fact, neither MSVC, GCC, or Clang are generating such spurious warnings. These warnings don't appear in the Appveyor (MSVC 2015), or Travis (GCC, Clang) logs.
If only some old version of MSVC generates this warning, perhaps a better fix is to just disable that warning for the offending compiler version.

**Comment by 1vanK** [comment]
Version of my VS is 2015...

**Comment by lunkhound** [comment]
I'm using Cmake/MSVC 2015/Win32 and I'm not getting those warnings.
Also if you look at the appveyor logs: [https://ci.appveyor.com/project/erwincoumans/bullet3/build/1.0.1934](url)
which is using MSVC 2015, I'm not seeing those warnings. All I see is 16 occurances of C4838, and those all look like legitimate warnings.
Hmmm.. I see that in my Cmake built Bullet project, certain warnings are disabled. It has warning C4244 (and also C4267) disabled.
Are you using premake?

**Comment by 1vanK** [comment]
> Are you using premake?

cmake

**Comment by lunkhound** [comment]
OK, now I can see where this is coming from. The warnings are coming from compiling external (non-bullet) source files that include that one bullet header.

In light of that, I agree this is a good change. I still think the warnings are pretty useless, but I also think it is kind of bad form for a third party library's headers to cause a spew of warnings.
Of all the ways to fix this, adding those 'f' suffixes is the least ugly option I can see.

**Comment by 1vanK** [comment]
Since when converting float to double there is no truncation, warning is also does not arise. So we can use float for all constants

**Comment by nicolaichuk** [comment]
associated PR https://github.com/bulletphysics/bullet3/pull/1052

**Comment by madebr** [comment]
This is fixed in current master.
This pr can be closed.

**Comment by 1vanK** [comment]
> You can already do btVector3(btScalar(1),btScalar(0.3),btScalar(0.3));
> Equally ugly and overly verbose indeed, hence the warnings are still there.

this is not same

https://stackoverflow.com/questions/55408191/is-literal-double-to-float-conversion-equal-to-float-literal

```
#include <utility>
#include <iostream>

using namespace std;

int main()
{
    float f1 =       1.0000000596046447753906250000000000000000000000000001f;
    float f2 = float(1.0000000596046447753906250000000000000000000000000001);

    if (f1 == f2)
        cout << "f1 == f2" << endl;
    else
        cout << "f1 != f2" << endl;
}
```

Output:

```
f1 != f2
```

**Pull request closed without merging**
