### PR TITLE
CMakeLists.txt search for any python version by default

### PR DESCRIPTION
**Pull request by ahundt**
Could https://github.com/bulletphysics/bullet3/pull/1334 be reverted so this can be applied?

See #1131 and https://github.com/bulletphysics/bullet3/issues/1322 for details on the evolution of these changes.

### CODE REVIEW

**Comment by erwincoumans** [comment]
There is some conflict. instead of reverting can you please create a clean client and just copy over some working cmakelists.txt file? Thanks for looking into this!

**Comment by ahundt** [comment]
@erwincoumans merged, hopefully everything behaves in a way that meets requirements this time. :-)

**Comment by erwincoumans** [comment]
Thanks for working on this, but:
Nope: -- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES) (found version "3.4.3")

**Comment by erwincoumans** [comment]
the current find python scripts finds it just fine:
https://travis-ci.org/bulletphysics/bullet3/jobs/280975587
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.4m.so (found version "3.4.3") 
so why does your updated script not find it there?

**Comment by ahundt** [comment]
@erwincoumans the script never previously searched for anything ending in an `m`. I updated it to include the `m` so it will look for `libpython3.4m.so` in addition to `libpython3.4.so` as a possible filename.

**Comment by ahundt** [comment]
@erwincoumans passes 👍

**Comment by erwincoumans** [comment]
Just in time for the 2.87 tagged release: https://github.com/bulletphysics/bullet3/releases/tag/2.87

**Pull request merged**
