### PR TITLE
clang format PhysicsServerCommandProcessor and BulletSoftBody

### PR DESCRIPTION
**Pull request by xhan0619**

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks a lot. Some binary .so file got added, could you remove it?
(make sure it doesn't show up in the history)

**Comment by xhan0619** [comment]
> Thanks a lot. Some binary .so file got added, could you remove it?
> (make sure it doesn't show up in the history)

Ah, sorry about that. I have removed it.

**Comment by erwincoumans** [comment]
LGTM, thanks!

**Comment by erwincoumans** [comment]
Thanks, LGTM! (and filed an issue to github, since  white space is not properly ignored:
https://github.community/t/ignoring-all-whitespace-changes-in-diff-including-split-merged-lines/811/5

**Pull request merged**
