### PR TITLE
Fixed constraint for btMultiBody and btRigidBody.

### PR DESCRIPTION
**Pull request by YunfeiBai**

### CODE REVIEW

**Comment by benelot** [comment]
Hi!Sounds like you know what you are doing! Would you be interested to add limits to the multibody joints as well? Also a quaternion PID is needed for the spherical joint. Just in case you would be interested to contribute :)

**Comment by erwincoumans** [comment]
Thanks for the contribution, I'll look at it asap.

@benelot The btMultiBody joints already have limits, see the btMultiBodyJointLimit abd examples loading URDF and SDF in example browser.

PID for spherical joint would be nice indeed, we could sork on that later.

**Comment by erwincoumans** [comment]
btMultiBodyJointLimitConstraint is the name. It works for revolute and prismatic joints of btMultiBody.

spherical joints are not used in many of the robots, so we haven't prioritized them.

**Comment by benelot** [comment]
@Erwin: I should have known that this might be one of your guys
contributing such a pull request :)

**Comment by erwincoumans** [comment]
Thanks for the help Yunfei!

**Pull request merged**
