### PR TITLE
Add nearly all gym environments using pybullet together with the…

### PR DESCRIPTION
**Pull request by benelot**
...latest tf model from the roboschool model zoo. All my examples try to connect to an already running ExampleBrowser and run headless if no browser is open (if somebody just wants the recording or the scores etc.).

For some reason, the model zoo version of reacher does not perform well at all. I will look into it again and otherwise just pull-request it here too since the env as such looks ok. If you want me to integrate the other gym envs you have into the same structure, just tell me. I can propose some structure for the gym stuff in general. Furthermore, I will soon pull-request my training pipeline so that people can also train stuff with the Example Browser.

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the environments, we have to discuss how this blends in with our existing efforts.

The 'enjoy' and 'train' follows the default naming of OpenAI baselines DQN training. We split our latest environments into a generic part (minitaur.py, kuka.py) and a gym specific part (kukaGymEnv.py, minitaurGymEnv.py). This split allows us to re-use the generic parts with proprietary/internal learning frameworks and DeepMind Sonnet etc.  For example:

KUKA : train_kuka_grasping.py + enjoy_kuka_grasping.py
MIT Racecar: train_pybullet_racecar.py + enjoy_pybullet_racecar.py
Cartpole: train_pybullet_cartpole.py + enjoy_pybullet_cartpole.py

1) Did you have a look at the structure of those environments?
2) Do you have the 'train' part?
3) A lot of the assets are already in the data folder, did you know that?

**Comment by benelot** [comment]
I have a train part I will commit soon. It allows to quickly combine an env and an agent and start the training. I also have an enjoy script which loads the latest stored checkpoint of a certain agent and runs it. I think this might be helpful within the example framework, it simplifies quick experiments. 

I did not yet look into your generic and env specific separation, I will check what this entails. Right, the assets are already there, so I will make my envs use those assets. Maybe I will have to update some of the assets to the newest version of OpenAI. I am also working on the remaining envs. Stay tuned for more. 

Just tell me how you would like to integrate this into the other envs. I can also propose some of my ideas.

**Comment by benelot** [comment]
Okay, so the separation of generic part and gym specific part basically does only make sense for the walkers. The pendula gyms can not be separated from the environment (except maybe if you want to separate the pendulum from the gravity :D).

From the others, I basically have to separate out the stadium scene. Would you like separate files for all the robots (just like your kuka and minitaur)? Otherwise, I am going to keep the same file structure and add another for all the *Env wrappers which then in turn load the respective robot and surrounding environment.

**Comment by benelot** [comment]
Is there a reason that some environments are called GymEnv and some are called BulletEnv? The repo is a bit messy in the gym part...

**Comment by benelot** [comment]
We now have a duplicate humanoid environment. Mine is the updated version from roboschool and it is also the version which is more handy to use for research as it is not just reduced to a bare minimum.

**Comment by erwincoumans** [comment]
Feel free to rename the existing humanoidGymEnv.py, it is not being used at the moment (simplehumanoid or so).
Also, once those environments work fine, it would be good to embed them in the pybullet distribution with assets, so you can simply instantiate them (like Gym and Roboschool allows).

**Comment by benelot** [comment]
Done. HumanoidGymEnv is called SimpleHumanoidGymEnv (and all related files respectively). All environments should work out of the box. You can give them a simple sanity check by running the respective enjoy_TF_* file. If an ExampleBrowser already runs, it runs with GUI, else it runs in headless mode (for training, that is great, maybe for the enjoy scripts not so much.) If you mean by 'simply instantiate them' that they can be instantiated like this:
`env = gym.make("AntBulletEnv-v0")`
then that is already done. Else, you tell me what is missing. Thanks!

**Comment by erwincoumans** [comment]
Great, thanks a lot!

>>If you mean by 'simply instantiate them'

On a clean computer, if you do "sudo pip install pybullet", the environments are not available at the moment. I need to fix the setup.py and MANISCRIPT.in files , so that you can easy access the environments, like Gym and Roboschool (including the data assets, and make sure python scripts find them properly). This is separate/independent from your pull request.

**Comment by erwincoumans** [comment]
By the way, the environments use the 2017may naming, shouldn't it be august?

**Comment by benelot** [comment]
The naming comes from the fact that they are the same trained networks as the ones from roboschool which were trained in may when I pulled them the last time.

**Comment by erwincoumans** [comment]
Sounds good. Did you already have a look at porting the Roboschool environments, like HumanoidFlagRun etc?

**Comment by erwincoumans** [comment]
Let's merge this CL, and go from there.

**Comment by benelot** [comment]
Thanks for merging! Yeah, I just had a look. They do not look like magic work, I can port them too. I also intend to add the training code I wrote in my bullet-gym repository. It helps to easily train different algorithms on the envs. This would complete the separation of agent, robot and environment. However, the training code still needs some work.

**Comment by ahundt** [comment]
Looks awesome, thanks guys!

**Comment by erwincoumans** [comment]
I just tried to run one of the new 'enjoy' environments on Mac OSX, got the following error:

Traceback (most recent call last):
  File "enjoy_TF_InvertedPendulumBulletEnv_v0_2017may.py", line 173, in <module>
    demo_run()
  File "enjoy_TF_InvertedPendulumBulletEnv_v0_2017may.py", line 25, in demo_run
    env = gym.make("InvertedPendulumBulletEnv-v0")
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/erwincoumans/dev/bullet3/examples/pybullet/gym/envs/gym_pendulum_envs.py", line 1, in <module>
    from scene_abstract import SingleRobotEmptyScene
ModuleNotFoundError: No module named 'scene_abstract'

**Comment by erwincoumans** [comment]
I had to modify the imports from scene_abstract to .scene_abstract.

Also, there is very ugly z-fighting because 2 ground planes are loaded: the green stadium AND the blue checkered mjcf ground. Why?

**Comment by erwincoumans** [comment]
image

**Comment by erwincoumans** [comment]
For now, I'll make the checkered ground plane invisible (alpha component = 0) like this:
                self.ground_plane_mjcf = p.loadMJCF("mjcf/ground_plane.xml")
                for i in self.ground_plane_mjcf:
                        p.changeVisualShape(i,-1,rgbaColor=[0,0,0,0])

**Comment by benelot** [comment]
Oh that is why there is the z-fighting, thanks for the update! I did not
realize that the mcjf still contained another plane.  We should probably
remove the plane from the mjcf file just as we did for the humanoid mjcf
(that also makes sense from the perspective of robot-environment
separation). I can do that in the next update of the envs which features
the other roboschool envs. I recently saw that you wrote an environment
(-helper) to produce the progressive terrain to reproduce the environment
from
https://deepmind.com/blog/producing-flexible-behaviours-simulated-environments/.
However, I could not find it again later. Can you tell me where to find it?
I could include it into the next update.

**Comment by erwincoumans** [comment]
I just refactored the gym envs, so that they can be easily imported/created from a pip install pybullet version. Work-in-progress. Due to moving files around/renaming, it may cause conflicts.
See https://github.com/bulletphysics/bullet3/pull/1265

It will be good to add some examples/tests out-of-the-box to demo pybullet/gym environments.

**Comment by benelot** [comment]
Ok, thanks for the update, I will try to rebase my newest work onto your
changes.

**Comment by erwincoumans** [comment]
I'm fixing the remaining data/path issues and upload a new version to pypi too. Also add some test/demo, perhaps your 'enjoy' scripts, so it is easy to try out pybullet for beginners.

The pybullet example to create a very simple parkour is called createObstacleCourse.py under bullet/examples/pybullet/examples.

**Comment by benelot** [comment]
Ok, so I will apply my changes to my own branch while keeping in mind that
you moved things. So as soon as you tell me you are done refactoring, I am
going to merge your stuff into my branch. If you need anything else, just
give me a shout. In the future, we can add a better version of the enjoy
scripts.

**Comment by erwincoumans** [comment]
How did you train the enjoy scripts exactly? I'm interested in trying it
out too.

enjoy_TF_HumanoidBulletEnv_v0_2017may.py,
enjoy_TF_Walker2DBulletEnv_v0_2017may.py
and enjoy_TF_HopperBulletEnv_v0_2017may.py work pretty well. THe other
'enjoy' scripts seem to need a bit more training/work.

**Comment by benelot** [comment]
I did not train those, it uses the exact same weights as the roboschool
demo scripts used a while ago (in May 2017 exactly). Unfortunately, they
have a non-published training framework (That is what Oleg told me at the
time I asked him, maybe it is working with baselines). But I achieved some
of the trainings too with my training code. I will update my training
framework to work with the newest envs we have here and then try to retrain
them. If I succeed to make some envs work with it, I can commit it with the
other scripts.

**Comment by erwincoumans** [comment]
It is better to move the 'connect' and 'disconnect' call inside the environments constructor/destructor, so that we can have multiple of them in parallel. Also, for multi-threading you have to pass the connection id to each call of pybullet (physicsClientId=..). I'll look into that. The minitaurGymEnv does this already.

**Pull request merged**
