### PR TITLE
Python API for GUI light source position adjustment, solving #2139

### PR DESCRIPTION
**Pull request by Pandhariix**
This PR proposes a __setLightPosition__ method, also available through pybullet, allowing the user to modify the position of the __light source__ in __GUI mode__ (it won't work in __DIRECT__ mode). It solves issue #2139.

The method can be used as pictured in the following snippet:
```python
pybullet.setLightPosition(15.0, 0.0, 15.0)
```

The method can be called several times at runtime:
light

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the contribution, that robot looks great!
I was considering re-using the pybullet.configureDebugVisualizer to set light position, configure shadow resolution etc. But since you already put in all the work, I'll consider merging it as-is after having a closer look.

**Comment by Pandhariix** [comment]
Thanks, it's our virtual Pepper model :) 
Wonderful! I'm not really familiar with the bullet code base, so I might have missed some things here and there, but globally I tried to match the way the other pybullet functionalities were implemented.

**Comment by erwincoumans** [comment]
There are some conflicts easy to resolve, could you do it in your PR? Thanks!

**Comment by Pandhariix** [comment]
Sure, the last commits should resolve them!

**Comment by erwincoumans** [comment]
Thanks for the update. I had a closer look and decided that it is better to add this feature in the 'configureDebugVisualizer', to keep it separate from the 'getCameraImage' which also has a lightPosition argument.
See https://github.com/bulletphysics/bullet3/pull/2298
This also exposes the shadowMapWorldSize and shadowMapResolution (texture resolution)
Thanks for the PR anyway!

**Comment by Pandhariix** [comment]
Very nice, I will use that feature a lot!

>  I had a closer look and decided that it is better to add this feature in the 'configureDebugVisualizer', to keep it separate from the 'getCameraImage' which also has a lightPosition argument.

It might be clearer that way, you're right. I also wanted to implement a way to control the intensity / color of the light source (as an extra parameter in _configureDebugVisualizer_ perhaps), do you think that it could be a relevant addition to the project ?

**Comment by erwincoumans** [comment]
Yes, if you want to create a PR to set light color/intensity to configureDebugVisualizer that is welcome.

**Comment by Pandhariix** [comment]
Alright, I'll surely submit a PR then.

**Comment by Kartoffelchen** [comment]
> Thanks for the update. I had a closer look and decided that it is better to add this feature in the 'configureDebugVisualizer', to keep it separate from the 'getCameraImage' which also has a lightPosition argument.
> See #2298
> This also exposes the shadowMapWorldSize and shadowMapResolution (texture resolution)
> There is an example in pybullet/examples/configureDebugVisualizer.py, like this
> 
> animate_light
> 
> Thanks for the PR anyway!

Is there any method to change the intensity of the light source? Thanks in advance!

**Pull request closed without merging**
