### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by dbartolini**

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
I was about to PR the same, the fix is correct. Here's an example warning with Emscripten:
```
error: field 'm_normalWorldOnB' will be initialized after field 'm_positionWorldOnB' [-Werror,-Wreorder-ctor]
```

I'd suggest also fixing indentation of `m_lateralFrictionDir{1,2}` while at it which were also added recently with space indentation instead of tabs.

**Comment by dbartolini** [comment]
Updated with indentation fix.

**Comment by dbartolini** [comment]
Rebased with indentation fix only.

**Comment by erwincoumans** [comment]
thanks, LGTM.

**Pull request merged**
