### PR TITLE
C api refactor build

### PR DESCRIPTION
**Pull request by goretkin**
An attempt at solving issue #2219

### CODE REVIEW

**Comment by goretkin** [comment]
There is a lot of "pybullet" flags that are checked in the C API build. All those configurations apply equally to the C API build as far as I can tell. So I'm not sure if they should be renamed, or just left as is.

**Comment by goretkin** [comment]
It looks like the test failure is spurious (some SSL timeout). I am not sure how to re-trigger it.

Is there anything in the way of getting this merged?

**Comment by erwincoumans** [comment]
Thanks for the contribution. I think the 'c_api' is similar to Bullet/Example/BulletRobotics?
If it doesn't break anything, let's merge it.

**Comment by goretkin** [comment]
Do you mean: https://github.com/bulletphysics/bullet3/tree/master/examples/BulletRobotics ?

Thanks for considering this merge. It will make it easier to wrap the project this way! Are you satisfied with the naming?

**Comment by erwincoumans** [comment]
No, it is this cmake target: https://github.com/bulletphysics/bullet3/tree/master/Extras/BulletRobotics

The subtle thing is that BulletRobotics doesn't depend on OpenGL/graphics, to keep the dependencies low. There is also a rudimentary C++ api on top of that BulletRobotics c api, to make it more confusing.
https://github.com/bulletphysics/bullet3/tree/master/examples/RobotSimulator

See https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/b3RobotSimulatorClientAPI_NoDirect.h
and
https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/b3RobotSimulatorClientAPI_NoGUI.h

**Comment by erwincoumans** [comment]
It seems your 'c_api' is a duplicate of the cmake BulletRobotics target in Extras/BulletRobotics.
If so, shall we remove it again, and make pybullet depend on BulletRobotics?

**Comment by goretkin** [comment]
If it's a duplicate, then that seems like the way to go! Could we rename BulletRobotics to something else, in analogy to pybullet?

And ideally, there would be a way to compile it with and without OpenGL support.

**Comment by erwincoumans** [comment]
best to revert it soon. It also breaks the build (we don't require OpenGL since we dynamically load it, not link it)

~~~~~~~~~~~~~~~~
OPENGL_gl_LIBRARY (ADVANCED)
    linked by target "bullet_c_api" in directory /home/travis/build/bulletphysics/bullet3/examples/c_api
OPENGL_glu_LIBRARY (ADVANCED)
    linked by target "bullet_c_api" in directory /home/travis/build/bulletphysics/bullet3/examples/c_api
~~~~~~~~~~~~~~~~

**Pull request merged**
