### PR TITLE
Add macro guard for compiling

### PR DESCRIPTION
**Pull request by xhan0619**

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks! It would be good to consider the conditional creation of a btDeformable*World instead of using the #ifdef SKIP_DEFORMABLE_WORLD. Let's discuss it soon.
Also, the ExampleBrowser demos don't show boundary faces for the tetrahedral meshes, can we add those too?

**Comment by xhan0619** [comment]
Yeah I'll add the faces for the demos in ExampleBrowser. We can discuss conditional creation tomorrow.

**Comment by erwincoumans** [comment]
Since the world creation is now determined at run-time, this PR can be closed?

**Comment by xhan0619** [comment]
> Since the world creation is now determined at run-time, this PR can be closed?

Yes, we should close it.

**Pull request closed without merging**
