### PR TITLE
add removeState in C++ API, see also Issue https://github.com/bulletp…

### PR DESCRIPTION
**Pull request by erwincoumans**
…hysics/bullet3/issues/2935

### CODE REVIEW

**Comment by aravindsiv** [comment]
Hi, I've added a follow-up comment to #2935 . But I am reproducing it here:

Even after I call `removeState()`, the memory al is not cleaned up until the end of `PhysicsServerCommandProcessor`'s lifetime. Is there a way to clean up the `savedState`'s `m_bulletFile` and `m_serializer` objects when we call `removeState()`?

**Comment by erwincoumans** [comment]
removeState IS deleting that memory, there is no leak. No need to wait for resetSimulation. Dis you apply my CL?

**Comment by aravindsiv** [comment]
I did, but I am still seeing no reduction in memory usage after I call `removeState` on all the stateIds I have saved so far. The stateId counter gets reset, but the memory doesn't appear to be deallocated.

**Comment by erwincoumans** [comment]
Me too, and there were no leaks. Please check https://github.com/bulletphysics/bullet3/issues/2935 and let me know if you see leaks/growing memory in that example. Let's discuss there, assuming you applied this pull request and no other modifications to the Bullet source code.

**Pull request merged**
