### PR TITLE
Cachebarycenter

### PR DESCRIPTION
**Pull request by fuchuyuan**
Add barycenter caching to static face constraints. Fix effective mass inverse not initialized for multibody node constraint.

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the report. I briefly tried out running the ExampleBrowser deformable examples. to check for regression. 
I think the ExampleBrowser "Deformables/Cloth Friction" example changed, once settled down, pick the red cloth, the blue should follow due to friction. Could you check it?

**Comment by fuchuyuan** [comment]
I turned off the option by default. Can you check again?

**Comment by erwincoumans** [comment]
I had a quick look, the deformable examples in the example browser seem to have degenerated before. It would be good to resolve this. You can see it by compiling/running the example browser and pick the "Cloth Friction" example. The cloth doesn't properly settle down and doesn't maintain a distance. (briefly perturb the blue cloth with the mouse). 

Do you know any parameters to change to make the sim more reasonable?

The "Deformable Self Collision" example seem to maintain some distance between the two cloths, but it has no friction. When enabling friction (psb->setFriction(3)), and carefully moving the bottom deformable/cloth doesn't reasonably move the top cloth.

**Comment by erwincoumans** [comment]
thanks, LGTM

**Comment by fuchuyuan** [comment]
Hi Erwin,

Sorry for the late reply.

The "Cloth Friction" example difference was due to tolerance of CR solver. You can restore the behavior by setting residual of btConjugateResidual to be 1e-4 instead of 1e-8. However, if you play around with 1e-4 a little bit, you will see the same not settling down behavior. This is because when the top cloth is in constraint with the ground, the cloth-cloth interaction will be ignored.


For The "Deformable Self Collision" example, I checked that the behavior is the same before and after the PR. You can set  psb->m_cfg.kDF = 10 and ground friction to be 0.1 to see top cloth being moved with the bottom one.

**Comment by erwincoumans** [comment]
Thanks Kelly, will check it out. By the way, if you have a minute, could you check out this reported cloth issue?
https://github.com/bulletphysics/bullet3/issues/3005

I haven't asked Xuchen to look at it yet, perhaps you have some suggestions for the issue?

**Pull request merged**
