### PR TITLE
Moved btLemkeSolver.h implementation in the proper cpp file

### PR DESCRIPTION
**Pull request by AndreaCatania**
This change move the implementation of btLemkeSolver inside the proper cpp file.
In this way I can stop the Godot compiler to complain when the flag -Werror is used.

### CODE REVIEW

**Comment by AndreaCatania** [comment]
Please let me know if this is an unwanted change so I can address it in another way

**Comment by akien-mga** [comment]
That should work fine for Godot's use case as we disable warnings for thirdparty libraries, so we won't get the warnings if it's in the `.cpp` file.

The warning itself would be worth fixing too though, which is:
```
In file included from thirdparty/bullet/btBulletCollisionCommon.h:61,
                 from thirdparty/bullet/btBulletDynamicsCommon.h:20,
                 from modules/bullet/godot_result_callbacks.h:37,
                 from modules/bullet/space_bullet.h:36,
                 from modules/bullet/space_bullet.cpp:31:
thirdparty/bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h: In member function 'virtual bool btLemkeSolver::solveMLCP(const btMatrixXf&, const btVectorXf&, btVectorXf&, const btVectorXf&, const btVectorXf&, const btAlignedObjectArray<int>&, int, bool)':
thirdparty/bullet/LinearMath/btQuickprof.h:198:50: error: declaration of '__profile' shadows a previous local [-Werror=shadow=local]
 #define BT_PROFILE(name) CProfileSample __profile(name)
                                                  ^
thirdparty/bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h:70:5: note: in expansion of macro 'BT_PROFILE'
     BT_PROFILE("inverse(slow)");
     ^~~~~~~~~~
thirdparty/bullet/LinearMath/btQuickprof.h:198:41: note: shadowed declaration is here
 #define BT_PROFILE(name) CProfileSample __profile(name)
                                         ^~~~~~~~~
thirdparty/bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h:46:4: note: in expansion of macro 'BT_PROFILE'
    BT_PROFILE("btLemkeSolver::solveMLCP");
    ^~~~~~~~~~
thirdparty/bullet/LinearMath/btQuickprof.h:198:50: error: declaration of '__profile' shadows a previous local [-Werror=shadow=local]
 #define BT_PROFILE(name) CProfileSample __profile(name)
                                                  ^
thirdparty/bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h:177:5: note: in expansion of macro 'BT_PROFILE'
     BT_PROFILE("lemke.solve");
     ^~~~~~~~~~
thirdparty/bullet/LinearMath/btQuickprof.h:198:41: note: shadowed declaration is here
 #define BT_PROFILE(name) CProfileSample __profile(name)
                                         ^~~~~~~~~
thirdparty/bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h:46:4: note: in expansion of macro 'BT_PROFILE'
    BT_PROFILE("btLemkeSolver::solveMLCP");
    ^~~~~~~~~~
```

Basically using `BT_PROFILE` twice in the same scope will generate this warning (with `-Wshadow=local` on recent GCC) as the macro will redefine a variable named `__profile` each time.

**Comment by AndreaCatania** [comment]
Hello, @erwincoumans do you have any news about this PR? Thanks in advance

**Comment by erwincoumans** [comment]
The thing is, when you add a cpp file, I need to fix several build systems internally, which takes some time. I'll try to look into it soon.

**Comment by erwincoumans** [comment]
How about we remove the duplicate BT_PROFILE in that file, instead of moving it into a cpp?

**Comment by erwincoumans** [comment]
Does this fix it? If not, please re-open:
https://github.com/bulletphysics/bullet3/commit/4d3ee40895efc8d0f6d3aed4e72c6aa40b313a09

**Comment by AndreaCatania** [comment]
Yes I'm pretty sure that this will fix the problem, Thanks!

**Pull request closed without merging**
