### PR TITLE
Step simulation and conversion between force and impulse use the same dt

### PR DESCRIPTION
**Pull request by fuchuyuan**
This commit fixes the inconsistency for getting contact force, and setting max joint torque when using substeps.

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the PR. Why do we need to store yet another variable, we could just add a method 'getFixedTimeStep' and compute it from m_physicsDeltaTime  and m_numSubSteps?

Also, we need to apply a similar fix for the contact points:

~~~~~~~~~~~~~~~~~~~
MyContactResultCallback cb(m_data->m_cachedContactPoints);

cb.m_bodyUniqueIdA = bodyUniqueIdA;
cb.m_bodyUniqueIdB = bodyUniqueIdB;
cb.m_deltaTime = m_data->m_physicsDeltaTime;

pt.m_normalForce = srcPt.getAppliedImpulse() / m_deltaTime;
pt.m_linearFrictionForce1 = srcPt.m_appliedImpulseLateral1 / m_deltaTime;
pt.m_linearFrictionForce2 = srcPt.m_appliedImpulseLateral2 / m_deltaTime;
~~~~~~~~~~~~~~~~~~~

**Comment by erwincoumans** [comment]
Applied a fixed here, please check:
https://github.com/bulletphysics/bullet3/pull/2809

**Comment by fuchuyuan** [comment]
> Thanks for the PR. Why do we need to store yet another variable, we could just add a method 'getFixedTimeSubStep' and compute it from m_physicsDeltaTime and m_numSubSteps?
> 
> Also, we need to apply a similar fix for the contact points:
> 
> ```
> MyContactResultCallback cb(m_data->m_cachedContactPoints);
> 
> cb.m_bodyUniqueIdA = bodyUniqueIdA;
> cb.m_bodyUniqueIdB = bodyUniqueIdB;
> cb.m_deltaTime = m_data->m_physicsDeltaTime;
> 
> pt.m_normalForce = srcPt.getAppliedImpulse() / m_deltaTime;
> pt.m_linearFrictionForce1 = srcPt.m_appliedImpulseLateral1 / m_deltaTime;
> pt.m_linearFrictionForce2 = srcPt.m_appliedImpulseLateral2 / m_deltaTime;
> ```

m_deltaTime is a member field of MyContactResultCallback so m_deltaTime should be used. But since MyContactResultCallback is only used here once either should be fine.

**Comment by fuchuyuan** [comment]
I don't have a strong preference wether we should add a method 'getFixedTimeSubStep' to avoid saving an extra field, or avoid recomputing. Either is fine with me.

**Comment by erwincoumans** [comment]
Sounds good, it is already merged in a separate PR.

**Comment by erwincoumans** [comment]
the PR missed various changes, here is a follow up PR:
https://github.com/bulletphysics/bullet3/pull/2815

**Pull request closed without merging**
