### PR TITLE
There was a typo I came across when cross compiling

### PR DESCRIPTION
**Pull request by ComradeKeys**
TLDR; I fixed a typo for the windows build.
 - bkeys

### CODE REVIEW

**Comment by erwincoumans** [comment]
We could fix this, but it makes me curious why you bother?
Is there a case sensitive windows compiler?

**Comment by scpeters** [comment]
seems to be an issue with cross-compiling with mingw:

* http://stackoverflow.com/a/15466951

**Comment by erwincoumans** [comment]
ah, didn't think of people cross-compiling windows executables. ok, then, let's apply it.
Thanks for the fix!

**Comment by ComradeKeys** [comment]
Yee, thanks for taking it.

**Pull request merged**
