### PR TITLE
pybullet tweaks for double precision

### PR DESCRIPTION
**Pull request by bingjeff**
* Converted floats to doubles in physics portion of pybullet.c, didn't touch rendering portion.
* Formatted the file into a consistent style (google C++ clang template)

### CODE REVIEW

**Comment by BluePrintRandom** [comment]
Slightly off topic, but could blender games implementation of bullets Float
precision also be improved with the same method?

**Comment by erwincoumans** [comment]
Looks good to me, thanks Jeff!

**Comment by bingjeff** [comment]
Glad to help Erwin!

@BluePrintRandom Not at all familiar with blender games or what ya wanna do, but if it is an interface issue with a wrapper then following the same approach seems likely. Good luck!

**Comment by erwincoumans** [comment]
@BluePrintRandom, Blender uses the single-precision version of Bullet (it doesn't #define BT_USE_DOUBLE_PRECISION) so this won't help you.

**Comment by BluePrintRandom** [comment]
Thank you Erwin,

have you seen upbge?

upbge is a fork of blender for game development,
it's open to contributers but I don't know c or c++ at the moment.

it's version of bullet is up for grabs for any aspiring developer who
wanted to start porting newer bullet features and tech to it.

panzergame and youle, lord loki and twisterGE could use any help any bullet
coders have modernizing the bge.

thanks again fellows!

**Pull request merged**
