### PR TITLE
Fix pendulum & manipulator envs with pybullet client

### PR DESCRIPTION
**Pull request by benelot**
You forgot to add the pybullet client to the pendulum environments. Thus they were no longer functional.

### CODE REVIEW

**Comment by benelot** [comment]
Awkwardly, there seem to be more commits on the list, but as you can see, I only changed some lines in 3 files, that is all.

**Comment by benelot** [comment]
There is the same problem with the manipulators too. That is why I appended the fix here too.

**Comment by benelot** [comment]
There are some other problems with all manipulators except the reacher. I will look into that soon.

**Comment by erwincoumans** [comment]
Thanks, I'll trust your PR improves the Gym environments.

**Pull request merged**
