### PR TITLE
Add documentation to notebook

### PR DESCRIPTION
**Pull request by davidcavazos**
Adds documentation to explain each step and have links to useful pages to improve the onboarding experience.

Staged: https://colab.sandbox.google.com/github/bulletphysics/bullet3/blob/656a1e74725933e947e5f64d465b62d6f9af683b/examples/pybullet/notebooks/HelloPyBullet.ipynb

### CODE REVIEW

**Comment by davidcavazos** [comment]
Can someone review or help this get merged? I think this would help a lot in the onboarding experience.

**Comment by erwincoumans** [comment]
Thanks. The installation of PyBullet should use pre-build wheels on Linux, so it takes about 20 seconds, not 5 minutes. Can you please amend it, and I'll merge it.
Note that there are some more advanced notebooks that can do hardware accelerated GPU rendering using OpenGL3, so you can faster and nicer looking images:
https://colab.research.google.com/drive/1u6j7JOqM05vUUjpVp5VNk0pd8q-vqGlx?authuser=1#scrollTo=7tbOVtFp1_5K

And another one training a model of a cartpole:
https://colab.sandbox.google.com/drive/15JSROMJbeiqxcUwifPR2NYeeFBKmyIlX#scrollTo=E2eWDjPZsQc5

**Comment by davidcavazos** [comment]
Thanks! It took some time to install a while ago but something must have changed, it is fast now. I've removed the notice :)

**Comment by davidcavazos** [comment]
@erwincoumans All tests are green! :)

**Comment by erwincoumans** [comment]
Thanks!

**Pull request merged**
