### PR TITLE
Replace HACD with V-HACD and add demo

### PR DESCRIPTION
**Pull request by AndresTraks**
V-HACD issue: https://github.com/bulletphysics/bullet3/issues/37

V-HACD forum thread:
http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=4&t=6619&start=15

### CODE REVIEW

**Comment by erwincoumans** [comment]
Great, thanks for the contribution! It is one of the first user-contributed examples using the new Example Browser :-) I'll have a look at it soon. It looks like the DLL version has a compile issue, perhaps you need to add a dependency to LinearMath library?

**Comment by AndresTraks** [comment]
It does seem like it. It works on Windows, but I can check Linux tomorrow.

**Comment by AndresTraks** [comment]
Ah, I think at some point LinearMath was no longer needed in HACD and the link was commented out from the build script. Now that V-HACD uses LinearMath again, the source code includes btConvexHullComputer.h and btAlignedObjectArray.h. But I left them out and included the ones in bullet instead without adding back the linker dependency to LinearMath.
Should work now.

**Comment by AndresTraks** [comment]
VHACD is included now, so I'll close this.

**Pull request closed without merging**
