### PR TITLE
General cleaning + typos + license header

### PR DESCRIPTION
**Pull request by elect86**
Also:

- [here](https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp#L1110-L1132) `body0` and `body1` can be null, but `gCalculateCombinedRestitutionCallback` expects them to be `!= null`

In fact at the end of `btDiscreteDynamicsWorld::integrateTransforms`, you check against that

- consider `ifdef`ing also [these two lines](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h#L76-L77) (as you did [here](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp#L78-L84)):
```	
        btCollisionAlgorithmCreateFunc* m_sphereBoxCF;
	btCollisionAlgorithmCreateFunc* m_boxSphereCF;
```

- in the [`SphereTriangleDetector::collide`](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp#L94), the `timeOfImpact` parameter is unused

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the PR, can you retrigger CI (commit small edit), since it failed likely due to unrelated other changes.

**Comment by erwincoumans** [comment]
close/reopen seems to trigger build

**Comment by elect86** [comment]
Removed also some duplicated code

**Comment by elect86** [comment]
Fixed build (crap VS didnt find any references..)

**Comment by elect86** [comment]
typo

**Comment by elect86** [comment]
Removed useless argument

**Comment by elect86** [comment]
Fixed build

**Comment by elect86** [comment]
Fixed build

**Comment by elect86** [comment]
Formatted a little more code and commented useless gl calls

**Comment by elect86** [comment]
Fixed build

**Comment by elect86** [comment]
Fixed color creation

**Comment by erwincoumans** [comment]
Unfortunately I don't have the bandwidth to spit through all those changes.

**Comment by elect86** [comment]
Sorry, but I'm not sure I really get what you meant.. what do you mean exactly?

**Comment by erwincoumans** [comment]
This is a very long list of small random changes and I have to sift through every line to make sure things don't break. I don't have the time to do that.
If you have some real bug fixes or new feature, please keep them to few files, with the essential parts, don't mix a large list of changes.

**Pull request closed without merging**
