### PR TITLE
[WIP] Adding joint limits to pybullet.getJointInfo(...).

### PR DESCRIPTION
**Pull request by benelot**
I am trying to add the joint limits to the pybullet.getJointInfo(...), but it still segfaults when I load a URDF (discussed here #959 ). I am working on it. All help welcome.

### CODE REVIEW

**Comment by benelot** [comment]
I am experiencing a strange issue with my changes where the jointName is messed up and the jointFriction and jointDamping are flipped with the newly introduced jointLowerLimit and jointUpperLimit. I am working on it to find out which of my changes messed this up.

**Comment by benelot** [comment]
The problem seems to be related to BulletFileLoader/autogenerated/bullet.h. How can I autogenerate this? If I directly edit it, I get the strangely messed up code I commited.

**Comment by erwincoumans** [comment]
The generation of serialization structures is not documented, and that autogenerated header file should never be manually changed: it needs to be in sync with the serialization 'DNA' in Bullet/src/LinearMath/btSerializer.cpp. The DNA stores the types and struct names, so that Bullet can do forward and backward compatibility, convert between 32bit and 64bit .bullet files and deal with enddianness differences and single float <-> double float precision etc.

1) There is a flag in the cmake build system that needs to be enabled.
2) Build and run makesdna and headerfile generator in  both 32bit and 64bit bit (copy the DNA string in a temp file, and combine both strings into btSerializer.cpp).
3) Run some example, so that the data/r2d2_multibody.bullet is using the new serialization structures.
4) run createDnaString.bat
5) create a CL / commit with all the changes in btSerializer (2 strings!) and bullet.h

For versioning it is best to create a new Bullet version, after major changes in the serialization structures, so I rather not have people contributing regular changes in that. It would be come a support burden and it is just easier to do it myself. Having said so, you are free to try it out, but I won't support you if you get stuck in the serialization procedures :-)

**Comment by benelot** [comment]
Thank you for pointing this out to me, I came to understand half of this from the various comments across the repository. I will clean my pull request from these changes and try to fix it with your guidance and make a separate commit for this. I would love to use it in my RL environments. Then, whenever you feel like it, you can merge this with the last commit or without it if you need to update serialization for your purposes anyway (in case you like my implementation).

**Comment by olegklimov** [comment]
Hey @benelot any progress on this?

I'm +1 on needing joint limits.

I also need effort limit and velocity limit.

**Comment by benelot** [comment]
Hey Oleg,

I did not finish this yet, but I can give it a try. It is basically done
within the code, but all it takes to finish is an update of the Bullet DNA,
which defines how Bullet serializes data (because it also serializes that
information). Where do you add effort limit and velocity limit? I can make
this work in the same run maybe.

**Comment by benelot** [comment]
BTW: I am working on some RL environments for OpenAI gym and I heard from Erwin you might be interested. Just drop me a mail if you have specific comments on what you are looking for or if you have an idea of a certain environment to implement (be.ellenberger@gmail.com). I am working with Erwin on an open-source community basis. You can have a look at my bullet-gym repo if you want to look at my current progress.

**Comment by olegklimov** [comment]
I wonder why Bullet needs serialization (.bullet files). A very limited use case, is it? Any game or simulator or Blender-like use case doesn't need it. I wish we could drop unnecessary code, simplify the library, have more time to improve structure, quality, accuracy and coverage of physics engine :(

Hello @benelot, I'm working on replacement of MuJoCo continuous control environments for Gym. Can you rebase your changes on top of master? It will be much easier to work with or merge. (it's hard in git but doable)

**Comment by benelot** [comment]
I just tried to make these serialization changes, but I am not sure if it worked. I will have to test it first. I already checked it in in case you want to check if it works. 

@olegklimov: Do you mean that I should rebase this PR on top of master? Or do you mean that I should rebase my bullet-gym changes on top of another master? I am not sure what you mean.

I already thought about a replacement of MuJoCo, since it is a commercial physics engine. Is that the reason for the replacement of the continuous control envs?

**Comment by olegklimov** [comment]
> rebase this PR on top of master? 

Right, this branch started a month ago.

> I already thought about a replacement of MuJoCo, since it is a commercial physics engine. Is that the reason for the replacement of the continuous control envs?

Yes.

**Comment by erwincoumans** [comment]
I'll update those serialization structures and create some document how to do it.

>> I wonder why Bullet needs serialization (.bullet files). 

It is used to save and restore the all of the state of Bullet. This is pretty important for robotics, machine learning and model predictive control. Also, the serialization is used in some games.

**Comment by olegklimov** [comment]
But are you saying that joint limits were not serialized?.. If it was unnoticed until now, hardly this code was ever used seriously.

I wish we could remove that DNA code and serialization, also disentangle URDF load from rendering and demos, move C API away from examples folder, isolate code for physics, and only add GPU code after existing code is simplified and test-covered. Minitaur and VR and Gym environments and rendering do not belong to physics engine, they are applications of physics engine.

If separation of concerns wasn't kept from the ground up, it's hard work to recover :(  Erwin maybe it's a good idea to at least start a "only remove and refactor code" policy?

**Comment by erwincoumans** [comment]
>> joint limits were not serialized?
Of course they were, but not as part of the new pybullet/C-API/URDF importers framework. I'll have a look if there is a better way to pass on the URDF data (instead of passing URDF parameters through the physics engine serialization structures)

>>Minitaur and VR and Gym environments and rendering do not belong to physics engine,

Those are examples of Bullet, the actual physics engine is all under Bullet/src code. You are just looking into examples, and pybullet, importers (URDF, SDF, MJCF etc), and Minitaur are all just examples, which many people find useful here. The pybullet + VR and C/Robotics/ML API is developing into a useful framework for robotics and machine learning used by various teams here inside Google. The python bindings, renderer (TinyRenderer) and visualizer (OpenGLWindow etc) and importers are pretty important parts of this framework.

At some stage I will move some parts of this examples/framework code into 'src' folder, and make the pybullet into an official project that you can easily install using setup.py/pip etc.

**Comment by olegklimov** [comment]
Let's take C API. Examples are little pieces of code that use the API of the library to show how to use it or how great and simple it is. Current C++ examples in Bullet:

* Not simple,
* Don't use C API,
* Interconnected,
* In fact, packaged into the library.

They were examples of C++ API, but not from the point of view of C API.

By definition, if you take VR project seriously, it is no longer an example, not little piece of code to show API usage.

I'm for taking C API seriously too, that's the point. First step is to define its scope: physics library should do physics and do it well. Not bundle GUI for example. Very little one can do with GUI from C API or Python, but it's there! 

And please don't get me wrong, I think Bullet is a great project and I'm trying to help: let's limit the scope of C API, make it work within this scope, not implement big separate software projects inside the library but rather gradually simplify and disentangle the code.

**Comment by erwincoumans** [comment]
Thanks for your feedback. To avoid mixing up things, there are 2 main APIs:
 
1) the Physics Engine API (such as Bullet 2.x and Bullet 3.x), in Bullet/src with examples such as See for example BasicDemo and HelloWorld. We shouldn't worry about this API right now.

2) the robotics machine-learning oriented API, such as pybullet, bullet3\examples\SharedMemory/PhysicsClientC_API.h and bullet3\examples\RoboticsLearning/b3RobotSimAPI.h (which is a new C++ wrapper around PhysicsClientC_API.h).

The scope of the (2) is described in the pybullet quickstart quide.
All this functionality is important, including URDF import, and basic built-in GUI front-ends (OpenGL Debug Visualizer and VR) and synthetic camera (getCameraImage). MuJoCo also has all of this functionality.

This built-in 'getCameraImage' is either using the TinyRenderer (about 500 lines of code) or the DebugVisualizer. For some projects, this built-in synthetic camera rendering is sufficient, but other projects may need a better renderer, so you can use any renderer and don't call the 'getCameraImage'. I'm not going to put a lot of resources to improve TinyRenderer, and like to see an example of using an external renderer.

It seems your project needs better debug visualization and/or synthetic camera rendering, and we should make it possible for you to connect the parts. We can also discuss how to re-organize some parts of re-usable code into libraries, possibly under Bullet/src or other location.

**Comment by erwincoumans** [comment]
One more thing to note: both the .bullet serialization and the new physics-client-server API share one important purpose: being able to easily reproduce problems/issues. Before I had the .bullet file format, it took a lot of effort/time to reproduce issues of developers, who integrated Bullet into their app (game, 3d modeler, movie plugin, robotics simulator like gazebo, ROS app etc). With the .bullet format, people can send me the .bullet file, and I can load it into my app (ExampleBrowser) to debug and visualize and see what is wrong. The physics client-server goes one step further: if you integrate the new physics API into an app (like gazebo, game, Blender etc), and you have some issue, you can 'connect' remotely to my machine over UDP or TCP, and I can put breakpoints, track down the issue, without having to touch the client code base (gazebo, Blender, ROS are huge difficult to debug beasts). I realize a lot of the rationale behind recent Bullet developments may not make much sense for a new developer looking into the code.

**Comment by olegklimov** [comment]
> send me the .bullet file, and I can load it into my app

Yeah that makes sense.

**Comment by erwincoumans** [comment]
By the way, if you use C++, I would suggest to look into the bullet3\examples\RoboticsLearning/b3RobotSimAPI.h. That should be a bit easier to use than the too-verbose C-API (bullet3\examples\SharedMemory/PhysicsClientC_API.h). Once all the methods from the C-API is into b3RobotSimAPI.h, I may re-implement pybullet.c using b3RobotSimAPI.

**Comment by olegklimov** [comment]
I don't see much improvement over C version. C++ has its advantages, specifically:

* STL helps with standard containers everyone knows how to use,

* `boost::shared_ptr<T>` lets you forget about memory management. I like to compare shared_ptr<> to python object that you pass in python without thinking. If you do the same in C++ program, it improves.

* Exceptions let you handle errors efficiently, also there is a possibility to convert C++ exceptions to Python exceptions, finally see "URDF file not found" when you load wrong file in python, without handling errors everywhere.

(less relevant here, I also see specific advantages in using `boost::asio` and `boost::thread`)

But I understand that's not going to happen, as Bullet should compile on variety on platforms, keeps complaint to older C++ standards.

**Comment by olegklimov** [comment]
I mean, to use this advantages, the whole program or library should follow this points. In single C++ interface, doesn't matter if it is C or C++, will make very little difference. Ability to delete object from simulation and correctly cleanup associated resources is more important IMHO for larger use cases.

**Comment by erwincoumans** [comment]
Let's get back to the original issue. The main issue here is that I re-used the Bullet 2.x serialization structures to pass URDF data. The URDF stores joint limits in a Joint structure. In Bullet, joints/links and their limits/motors are split between btMultiBody, btMultiBodyLink and btMultiBodyConstraint (in case you use multibody. If using maximal coordinates, this data is stored in btRigidBody and btTypedConstraint). For now, I'll adapt the Bullet 2.x serialization structures, but eventually we need a separate internal structure to transmit such data between server and client.

**Comment by benelot** [comment]
Erwin, do you want me to clean up this PR or do you modify it yourself (including the update to the serialization structure) to merge it?

**Comment by erwincoumans** [comment]
@benelot Please keep this pull request open, I'll re-do it and create another pull request, once done we can close both.

**Comment by benelot** [comment]
I think this is done, so we can close it.

**Pull request closed without merging**
