### PR TITLE
isAlive method forcing done=False for halfcheetah

### PR DESCRIPTION
**Pull request by alexis-jacq**
As suggested in https://github.com/bulletphysics/bullet3/pull/1759. 

I had to pass the 'alive' condition as an additive parameter of WalkerBaseBulletEnv.

### CODE REVIEW

**Comment by erwincoumans** [comment]
Is only Half-Cheetah affected? Do the other environments (Humanoid, Ant etc) train with with ARS with the original PyBullet reward/done?

**Comment by alexis-jacq** [comment]
Half-Cheetah is the only one that overwrites the method, so it should be the only one affected. 
With ARS, Half-Cheetah seems ok, Humanoid and Ant are longer to train. I tell you asap if they worked.

**Comment by hadelin2p** [comment]
We need to have three different 'done' for Half-Cheetah, Ant and Humanoid, if we want to use the same as in Mujoco (which I think we should since replacing 'done = alive < 0' by 'done = False' made Half-Cheetah work successfully). The 'done' in MuJoCo are as follows:

**Half-Cheetah:**
`done = False`

**Ant:**
```
notdone = np.isfinite(state).all() and state[2] >= 0.2 and state[2] <= 1.0
done = not notdone
```

**Humanoid:**
```
qpos = self.sim.data.qpos
done = bool((qpos[2] < 1.0) or (qpos[2] > 2.0))
```

**Comment by erwincoumans** [comment]
can you implement those?

**Comment by hadelin2p** [comment]
Sure we will do that this evening

**Comment by erwincoumans** [comment]
isDone method is more clear than 'isAlive', since it is passed through Gym interface as 'done' boolean.
Thanks for the help!

**Comment by erwincoumans** [comment]
Thanks, LGTM.

**Pull request merged**
