### PR TITLE
Changed "eglrendertest.py":Windows Error

### PR DESCRIPTION
**Pull request by NiranthS**
Hello sir
I have changed "GUI" to "DIRECT" in eglrendertest.py file

### CODE REVIEW

**Comment by NiranthS** [comment]
Update of "eglRenderTest.py" is shown at the last

**Comment by erwincoumans** [comment]
I have to thing about how to do this.
When you compile pybullet using premake/cmake, the pybullet_data module is often not available. Then the old examples still work fine, as long as you run them from that folder.
Now with your changes, it breaks that functionality, since it will abort importing a non-existing pybullet_data module. So we need to wrap the import pybullet_data inside a 'try' statement, and only setAdditionalSearchPath if that exists. It becomes messy...

**Comment by NiranthS** [comment]
Oh okay

**Comment by NiranthS** [comment]
Hello sir
I am Niranth Sai from the Indian Institute of Technology (BHU) Varanasi. We
were planning to introduce pybullet to the students in our institute as a
default simulator for our projects. We found pybullet better than gazebo
simulator in many aspects(easy to learn and use, moreover it is a python
module so it will be easy to implement Machine Learning related stuff in
the simulator).
We would like to have your suggestions/tips on how to go on to introduce
pybullet to the students here.
                                              Thank You
Yours Sincerely
Niranth Sai




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/25/20,
02:50:46 PM

On Fri, Apr 24, 2020 at 8:57 PM Sirusala Niranth Sai 4-Yr B.Tech.
Electronics Engg., IIT(BHU), Varanasi <sirusalansai.ece18@itbhu.ac.in>
wrote:

**Comment by erwincoumans** [comment]
Reconsidering, since some of the examples already require pybullet_data, let's apply the patch. Thanks for the contribution.

It is up to you how to organize your classes, hope PyBullet will be useful, also consider using Google Colab and Stable Baselines (to train / enjoy reinforcement learning).

**Comment by NiranthS** [comment]
Yeah sure😄

**Comment by NiranthS** [comment]
Thanks a lot for the example.

**Pull request merged**
