### PR TITLE
Adding synchronization of pose transforms of eglPlugin with m_instancingRenderer

### PR DESCRIPTION
**Pull request by dchichkov**
Somewhat addresses rendering from the eglPlugin.  At least the transformations are synchronized to the m_instancingRenderer.    Please note, I've cherry-picked the changes from a private branch, tested that it builds, but can't currently run the test (GPU memory is busy elsewhere, training stuff).

Code to reproduce is below:

```
import pybullet as p, os, sys

if sys.argv[1] == "glx":
    p.connect(p.GUI)
elif sys.argv[1] == "egl":
    p.connect(p.GUI, options='--window_backend=2 --render_device=0')
elif sys.argv[1] == "tiny":
    p.connect(p.DIRECT)
elif sys.argv[1] == "plugin":
    p.connect(p.DIRECT)
    p.loadPlugin(p.__file__.replace("pybullet", "eglRenderer"), "_tinyRendererPlugin")
else:
    print("args should be [glx|egl|plugin|tiny]")
    sys.exit(1)

p.setAdditionalSearchPath("data")

width,height,viewMatrix,projectionMatrix = 128, 128, (0.9999997019767761, 0.00036114765680395067, -0.0006804274744354188, 0.0, -0.00036628328962251544, 0.9999714493751526, -0.007562750019133091, 0.0, 0.0006776766385883093, 0.007562996819615364, 0.9999712705612183, 0.0, 0.0007347110076807439, 0.09311465173959732, -0.22162719070911407, 1.0), (3.732050895690918, 0.0, 0.0, 0.0, 0.0, 3.732050895690918, 0.0, 0.0, 0.0, 0.0, -1.040816307067871, -1.0, 0.0, 0.0, -0.040816325694322586, 0.0)


print(p.getQuaternionFromEuler([0.0, 0.0, 0.0]))
plane = p.loadURDF("plane.urdf")
cube = p.loadURDF("cube.urdf",(-0.2, -0.6, 0.05), (0.0, 0.0, 0.0, 1.0))

if sys.argv[1] in ("egl", "glx"):
    _,_,rgba,_,_ = p.getCameraImage(width=width,height=height,viewMatrix=viewMatrix,projectionMatrix=projectionMatrix, renderer=p.ER_BULLET_HARDWARE_OPENGL)
else:
    _,_,rgba,_,_ = p.getCameraImage(width=width,height=height,viewMatrix=viewMatrix,projectionMatrix=projectionMatrix)

from PIL import Image
Image.frombuffer('RGBA', (width,height), rgba, 'raw').save("0." + sys.argv[1] + ".png")

```

python3 giu.py egl ; python3 giu.py glx ; python3 giu.py plugin ; python3 giu.py tiny

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks. Actually I started looking into the plugin and already fixed those things, picked from your patch. I'll upload a patch in a minute.

Also I fixed the up axis and light direction, so it look already more like the regular 'GUI' mode. Obviously the main benefit of this plugin is that it can run in EGL mode in a headless server/cloud environment.
Thanks for your PR anyway!

45268603-91f6c300-b433-11e8-842c-d5ab7f3b6c9c

**Comment by erwincoumans** [comment]
How are you building the plugin? The premake4 file was a bit out-of-date. I updated the premake for Windows (using Win32OpenGLWindow), will update the premake build for Linux and Mac later.

**Comment by erwincoumans** [comment]
Here is the PR: https://github.com/bulletphysics/bullet3/pull/1869 with similar changes to this PR.
I added a credit/mention to your fix in the description of my PR.

**Comment by dchichkov** [comment]
I've patched the pybyllet/CMakefile.txt to compile statically eglPlugin instead of TinyRenderer, and then I was using build_cmake_pybullet_double.sh.  Also, setup.py build actually worked as well - it builds eglplugin.so, which in turn could  be loaded by the following hack:
`  p.loadPlugin(p.__file__.replace("pybullet", "eglRenderer"), "_tinyRendererPlugin")`

By the way, I've hacked-in TensorRT support into the plugin/egl. It runs inference directly in the GPU memory, and then return a feature vector, instead of an image.  Calling it with:
.getCameraImage(width=feature_vector_width, height=1, ... , renderer=pybullet.ER_CALCULATE_FEATURES).   

If you are interested, I can put together a PR.

**Comment by BlGene** [comment]
@dchichkov:
closer integration of simulation and computational models is a good idea. I would however suggest achieving this by using CUDA's OpenGL/EGL Interoperability to copy data to Tensorflow, i.e. turning the simulation into an TF Op that takes as input the actions and returns an observation tensor. This would be easier to integrate into existing RL code.

**Comment by erwincoumans** [comment]
Yes, please share some example of TensorRT, I haven’t used it yet. We
primarily use TensorFlow for our robots and RL with OpenAI Gym environments
using PyBullet.

**Comment by dchichkov** [comment]
Ok. And closing this PR.

**Comment by erwincoumans** [comment]
By the way, I'm now using this in the examples:

import pkgutil
eglPath = pkgutil.get_loader('eglRenderer').get_filename()
p.loadPlugin(eglPath, "_eglRendererPlugin")

**Pull request closed without merging**
