### PR TITLE
port the rbdl into the bullet as well as write a simple test to compa…

### PR DESCRIPTION
**Pull request by Steven89Liu**
…re the ABA between the bullet and the rbdl, including:

1. download the rbdl from the https://bitbucket.org/rbdl/rbdl/downloads/?tab=downloads, (rbdl-rbdl-0879ee8c548a.zip)
2. change three CMakeList.txt and remain the original file there as CMakeList.txt-orig,
3. add a m_flag in the class MyBtMultiBodyFromURDF to indicate that if using the inertia value from the urdf file, or other usage in the future,
4. add a test test/InverseDynamics/test_dynABA_bulletVSrbdl.cpp to compare the ABA between the rbdl and the bullet.

### CODE REVIEW

**Comment by erwincoumans** [comment]
I love this comparison and am going to check it out. I find adding the whole RBDL library as dependency in Bullet too large. Wonder if the forward dynamics can be compared similar to the inverse dynamics, purely in Python, like the RBDL/KDL/Pybullet comparison of inverse dynamics?
https://github.com/bulletphysics/bullet3/issues/2246

**Comment by Steven89Liu** [comment]
i think it is more better to add the whole RBDL libray for the first version, we can delete some unused part in next version.  
It should can be implemented in Python, i will look into this later.

**Comment by erwincoumans** [comment]
It is not a good idea to add full other dynamics libraries into Bullet, it clutters the git history and confuses the users into thinking Bullet depends on those external libraries (which is not the case).

**Comment by Steven89Liu** [comment]
OK, i will delete these unused part.

**Comment by Steven89Liu** [comment]
”The job exceeded the maximum time limit for jobs, and has been terminated.“
don't know what this error mean, i will check it again tomorrow.

**Comment by Steven89Liu** [comment]
Could you help to merge this PR?

**Comment by erwincoumans** [comment]
Sorry I wasn't clear, but I don't want to add any RBDL files into Bullet.  One option is to add a continuous integration test (travis, appveyor) that pulls the rbdl files (specific revision) into the right location. So we only need to add an option to enable this RBDL comparison test (it is disabled by default!) and the test itself.

**Comment by erwincoumans** [comment]
I'll try to find time soon, to only add the test file itself, without RBDL, and merge it into Bullet.

**Comment by erwincoumans** [comment]
Thanks a lot, this can be merged.

**Pull request merged**
