### PR TITLE
Soft body exp

### PR DESCRIPTION
**Pull request by fuchuyuan**
This PR does the following changes:
1. Turn on SoftDemo in ExampleBrowser
2. Adds setting startPosition and startOrientation options to b3RobotSimulatorClientAPI_NoDirect
3. Adds setting startPosition and startOrientation options to pybullet

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the patch. It contains a mix of spaces and tabs. Bullet uses tabs at the moment, can you please run the clang-format on the files you modified (not on ALL files)?

**Comment by fuchuyuan** [comment]
Formatted files!

**Comment by erwincoumans** [comment]
Now the CL has tons of white space changes. Please undo all of it. A CL with whitechanges should exclusively have whitespace changes.

**Comment by erwincoumans** [comment]
Thanks, LGTM.

**Pull request merged**
