### PR TITLE
don't use glSwapAPPLE, it fails on some OSX versions

### PR DESCRIPTION
**Pull request by erwincoumans**
thanks Steven for the report

### CODE REVIEW

**Comment by scpeters** [comment]
Sorry, now I get the following on Yosemite:
~~~
/Users/scpeters/osrf/bullet3/examples/OpenGLWindow/MacOpenGLWindow.mm:1041:29: error: instance variable
      'm_context' is protected
 [m_internalData->m_myview->m_context flushBuffer];
                            ^
1 error generated.
~~~

**Comment by scpeters** [comment]
We should set up CI for OS X as well.

**Comment by scpeters** [comment]
It fails on both yosemite and mountain lion for me.

**Comment by erwincoumans** [comment]
Yes, we should setup CI for various versions of OSX, because fixing it in one version can still be broken in another, as we noticed a few times. Do you have time to help set it up with appveyor or travis?

In the meanwhile, I have a fix ready, commit in a few minutes :-)

**Comment by erwincoumans** [comment]
if you have time, please try this one: 
https://github.com/bulletphysics/bullet3/pull/376

**Comment by scpeters** [comment]
testing...

**Comment by scpeters** [comment]
looks good on ubuntu 14.04, yosemite and mountain lion

**Comment by scpeters** [comment]
~~~
ndefined symbols for architecture x86_64:
  "GLPrimitiveRenderer::setScreenSize(int, int)", referenced from:
      SimpleResizeCallback(float, float) in SimpleOpenGL3App.o
  "GLPrimitiveRenderer::drawTexturedRect3D(PrimVertex const&, PrimVertex const&, PrimVertex const&, PrimVertex const&, float*, float*, bool)", referenced from:
      SimpleOpenGL3App::drawText3D(char const*, float, float, float, float) in SimpleOpenGL3App.o
  "GLPrimitiveRenderer::GLPrimitiveRenderer(int, int)", referenced from:
      SimpleOpenGL3App::SimpleOpenGL3App(char const*, int, int) in SimpleOpenGL3App.o
  "GLInstancingRenderer::InitShaders()", referenced from:
      SimpleOpenGL3App::SimpleOpenGL3App(char const*, int, int) in SimpleOpenGL3App.o
  "GLInstancingRenderer::GLInstancingRenderer(int, int)", referenced from:
      SimpleOpenGL3App::SimpleOpenGL3App(char const*, int, int) in SimpleOpenGL3App.o
  "OpenGL2RenderCallbacks::OpenGL2RenderCallbacks(GLPrimitiveRenderer*)", referenced from:
      SimpleOpenGL3App::SimpleOpenGL3App(char const*, int, int) in SimpleOpenGL3App.o
  "_stbi_write_png", referenced from:
      SimpleOpenGL3App::swapBuffer() in SimpleOpenGL3App.o
ld: symbol(s) not found for architecture x86_64
~~~

**Comment by erwincoumans** [comment]
How do I replicate this? I never use BUILD_SHARED.
I tried running this, but couldn't replicate an error on Yosmite:
cmake .. -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
make

**Comment by scpeters** [comment]
It works on yosemite, just not on Mountain Lion.

You can decide how much you want to support.

**Comment by scpeters** [comment]
I'll try Mavericks as well

**Comment by scpeters** [comment]
works on Mavericks, the only failure I see is on Mountain Lion.

**Comment by scpeters** [comment]
It could be a bug in the linker?

**Comment by scpeters** [comment]
The `GLPrimitiveRenderer` is [disabled if OpenGL3 is not available](https://github.com/bulletphysics/bullet3/commit/0da584a42d1dc8792f2efd6e169cea6b5dc0caf8#diff-07c1d8af86c634224739c8b549cd999eR1). I don't know why the shared library linker wants to see them.

**Comment by erwincoumans** [comment]
So the static version works fine, just the shared lib version on Mountain Lion is broken?
Then I'm happy to go ahead with marking a new release.

**Comment by scpeters** [comment]
It's complaining about symbols from `SimpleOpenGL3App.o`; I thought those were disabled. Can we double check that logic really quick?

**Comment by scpeters** [comment]
I think [SimpleOpenGL3App](https://github.com/bulletphysics/bullet3/blob/master/examples/OpenGLWindow/SimpleOpenGL3App.cpp) is being compiled on Mountain Lion. We should only compile that if OpenGL3 is available right? I think that is causing the linking errors.

**Pull request merged**
