### PR TITLE
pybullet support for gym BREAKING CHANGES, including v0.9.x

### PR DESCRIPTION
**Pull request by wenkesj**
This adds support for the latest `gym` releases `v0.9.x` which includes a breaking change when extending `gym.Env`: [v0.9.5](https://github.com/openai/gym/releases/tag/v0.9.5) and [v0.9.6](https://github.com/openai/gym/releases/tag/v0.9.6). Backwards compatibility for `gym < v0.9.x` is maintained without any major changes.

### CODE REVIEW

**Comment by wenkesj** [comment]
I'm sorry about the whitespace removal >_<, I didn't notice...

**Comment by erwincoumans** [comment]
Does this make pybullet incompatible with older Gym versions (pre- 0.9.5)?

Can you re-do the pull request without the white-space changes?

**Comment by wenkesj** [comment]
@erwincoumans I appreciate the response. 

I made the decision to add "proxy" methods _on-top-of_ the original `gym < 0.9.x` methods that cause issues when adapting `>= v0.9.x`, where the `_step, _reset, _etc.` methods are not just depreciated, they are removed and replaced with `step, reset, etc.`. 

I believe if developers adapt this "proxy" methodology, versions `< 0.9.x AND >= 0.9.x` will be supported and maintained without a problem or further changes.

And yes, I will remove the white space changes :)

**Comment by wenkesj** [comment]
@erwincoumans can these changes be verified by the CI, I assume it's difficult and may not be necessary (i.e. using 2 version of `gym`)? Or is there one for the module?

**Comment by benelot** [comment]
In what way was there no pybullet support for gym before this? I do not see yet, what were the crucial changes.

**Comment by wenkesj** [comment]
@benelot there was gym support before this, for gym version < 0.9.x, please see this [https://github.com/openai/gym/releases/tag/v0.9.6](https://github.com/openai/gym/releases/tag/v0.9.6) 

More specifically, 

> Now your Env and Wrapper subclasses should define step, reset, render, close, seed rather than underscored method names.

**Comment by wenkesj** [comment]
@benelot 

```python
import gym

class TestEnv(gym.Env):

  def _step(self, action):
    return None, None, None, None

  def _reset(self):
    return None


env = TestEnv()
env.reset()
```

This raises the following:

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    env.reset()
  File "python3.6/site-packages/gym/core.py", line 70, in reset
    raise NotImplementedError
NotImplementedError
```

**Comment by benelot** [comment]
Thanks for mentioning. Now I know :)

**Comment by erwincoumans** [comment]
ok, sounds good. Thanks for the contribution.

**Pull request merged**
