### PR TITLE
Add link name to getJointInfo(...).

### PR DESCRIPTION
**Pull request by benelot**
PR to #1066. Just added the linkName to getJointInfo(...). Is this sufficient or should I create a new command to get link specific info such as getLinkInfo(...)?

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks, looks good to me.

**Comment by ShravanTata** [comment]
@benelot It would be much better to have getLinkInfo to extract link names rather than from getJointInfo. Could we reopen this issue to fix this? Thanks

**Comment by erwincoumans** [comment]
Does the linkname returned by getJointInfo not work for you? If not, reopen and describe a repro case.

**Comment by ShravanTata** [comment]
Found an important information that helped me solve this issue.
In bullet linkIndex == jointIndex

Using the above, I currently have the following solution below

_link_name_to_index = {p.getBodyInfo(model_id)[0].decode('UTF-8'):-1,}
        
for _id in range(p.getNumJoints(model_id)):
	_name = p.getJointInfo(model_id, _id)[12].decode('UTF-8')
	_link_name_to_index[_name] = _id

**Comment by submagr** [comment]
`In bullet linkIndex == jointIndex`

But a robot can have more links than the joint, right? For example: l1---j1---l2. This robot has two links connected by a joint. The reason I ask this question is if I want to do calculateInverseKinematics for l2, pybullet raises index out of range error.

**Comment by ignacioDeusto** [comment]
It misses the root link (at least in my case).
For instance, in your example:
l1 -> missed
j1 -> joint index 0
l2 -> link index 0
When checking for collisions, l1 is expressed as -1 link, but there's no link index -1, if you try to check the -1 index link state it crashes.
Missing the first link ensures that the number of joints equals the number of links. The main limitation with the current approach is that you can't get the root link name, also this one on one relation between joints and links feels weird for newcomers.

**Comment by ShravanTata** [comment]
`p.getBodyInfo(model_id)[0].decode('UTF-8')` returns the base link name. [Code above](https://github.com/bulletphysics/bullet3/pull/1082#issuecomment-516545497) should return all link names including the base/root link

**Pull request merged**
