### PR TITLE
Suppressing a Few UBSan Issues with getHash

### PR DESCRIPTION
**Pull request by m-chaturvedi**
re https://github.com/bulletphysics/bullet3/issues/1228

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the report of UBSan issues, I've never used UBSan but will try it out too.
For the fix, I prefer fixing the code instead of disabling checks for particular compilers. I'll have a look at it once I have time or you can suggest some code fixes for this.

**Comment by m-chaturvedi** [comment]
Sure, thanks!
I'm not sure if there's any fix which will not make the code complicated.

**Comment by m-chaturvedi** [comment]
Did you get a chance to have a look at it?  Thanks!

**Comment by erwincoumans** [comment]
No volunteer shows up in fixing this hash function, so for now just suppress the warning.
If someone has a fix, re-open and provide a pull request.

**Pull request closed without merging**
