### PR TITLE
Create Inclined Plane, Newton's Cradle and Multi-Pendulum examples for the Bullet Example Browser

### PR DESCRIPTION
**Pull request by benelot**
My contributions to the tutorials series. More things to come.

### CODE REVIEW

**Comment by benelot** [comment]
Yay! I did it :+1:

**Comment by benelot** [comment]
Is there something wrong with my commit that the appveyor fails? I can not see anything particular in the details that is related to me.

**Comment by erwincoumans** [comment]
Did you search for 'error' in the build log, by right-clicking on 'Details' on AppVeyor build fails?
https://ci.appveyor.com/project/erwincoumans/bullet3/build/1.0.745
The first error is related to M_PI, Bullet uses SIMD_PI as cross-platform alternative, defined in btScalar.h.

C:\projects\bullet3\examples\ExtendedTutorials\InclinedPlane.cpp(92): error C2065: 'M_PI': undeclared identifier [C:\projects\bullet3\cmake\examples\ExampleBrowser\App_ExampleBrowser.vcxproj]

**Comment by benelot** [comment]
Fixed the issues and all compiles well. I somehow overlooked the M_PI problem. Thanks for pointing that out. I also cleaned up my conversion warnings to unclutter the compile. 

More examples to come soon!

**Comment by erwincoumans** [comment]
The Newton cradle could better be simulated using two ropes attached to each ball. Can you please checkout the ExampleBrowser/SoftBody/Rope Attach demo?
See image here: http://www.academyofscienceforkids.com/newton-cradle-motion

**Comment by benelot** [comment]
That is true and it could also look very nice. I will add a Newton's Rope Cradle example then. I will leave this one for simplicity and add the one with the rope as another example for a more advanced rope usage.

**Comment by benelot** [comment]
I am trying to connect two bodies using this method, however I get crashes in btSoftBody::updateBounds()

This is basically the method I am using to connect them:

```
void NewtonsRopeCradleExample::connectWithRope(btRigidBody* body1, btRigidBody* body2)
{
        btSoftBody* softBodyRope0=btSoftBodyHelpers::CreateRope(m_softBodyWorldInfo,body1->getWorldTransform().getOrigin(),body2->getWorldTransform().getOrigin(),8,0);
        softBodyRope0->setTotalMass(50);

        softBodyRope0->appendAnchor(softBodyRope0->m_nodes.size()-1,body1);
        softBodyRope0->appendAnchor(0,body2);

        //softBodyRope0->m_cfg.piterations = 5;
        //softBodyRope0->m_cfg.kDP = 0.005f;

        getSoftDynamicsWorld()->addSoftBody(softBodyRope0);
}
```

I am probably missing something in the setup of the softbody world, however I can not find what it could be.

**Comment by benelot** [comment]
I fixed the issue (by starting again from the simple cloth example), however, the example does not yet work as expected. Stay tuned.

**Comment by benelot** [comment]
Is there a way to change the springiness of a rope? Currently the cradle balls bounce like they are on rubber bands.

**Comment by benelot** [comment]
Here are the updates for the old and the additional new example.

**Comment by benelot** [comment]
Any comments on this? I would be happy to have my first contribution pulled in.

**Comment by erwincoumans** [comment]
Thanks for working on this. It breaks the Windows build, using premake. Missing files in premake (fixed by attached patch) and parameters such as btVector3/btQuaternion needs to be passed as const reference, not by value (it causes SIMD alignnment errors on Windows).

 I need to figure out how to re-enable premake builds, in addition to cmake builds in 

Aside from that, it would be great if there is a way to activate the Newton cradles by GUI or just at the start. Not a showshopper though :-)
[premake.zip](https://github.com/bulletphysics/bullet3/files/357677/premake.zip)

**Comment by benelot** [comment]
Fixed and improved! :) Anything else?

**Comment by erwincoumans** [comment]
Thanks for the work on this. Once I play with the Newton Cradles, they become a big mess immediately. What I meant was: remove all the sliders and make it so that it works without any user interaction. Just a Cradle that moves at startup.

**Pull request merged**
