### PR TITLE
Convert DOS (CRLF) source files to Unix (LF) line endings

### PR DESCRIPTION
**Pull request by akien-mga**
Excluded `examples/pybullet/gym/pybullet_data/` which has many (3000+)
CRLF data files (obj, mtl, urdf), and `docs/pybullet_quickstart_guide`
which has generated .js and .htm files with CRLF line endings too.

----

Before this change:
```
$ grep --exclude-dir={.git,data,docs,examples} -IUlr $'\r' | wc -l
18
$ grep --exclude-dir={.git,data,docs,examples} -IUlr $'\n' | wc -l
1085
```

After:
```
$ grep --exclude-dir={.git,data,docs,examples} -IUlr $'\r' | wc -l
0
$ grep --exclude-dir={.git,data,docs,examples} -IUlr $'\n' | wc -l
1085
```

### CODE REVIEW

**Comment by akien-mga** [comment]
Note: will likely conflict with #2264 which fixes encoding in a file with CRLF line endings, but I can rebase either as needed.

**Comment by erwincoumans** [comment]
We use clang-format for formatting. It is much faster if I run that tool myself, I don't have time to sift through tons of files, making sure no other change slipped though.

I'll run clang-format again soon, to make sure formatting is ok. At the moment it is only used on .h and .cpp files, no .mk or txt.

**Comment by akien-mga** [comment]
AFAIK clang-format doesn't impact line ending characters.

**Comment by akien-mga** [comment]
You can use `?w=1` to see changes without whitespace changes: https://github.com/bulletphysics/bullet3/pull/2265/files

Or run `dos2unix` on those files yourself if you prefer.

**Comment by erwincoumans** [comment]
OK, ?w=1 resolves the issue, I'll accept it. Thanks for the help!

**Pull request merged**
