### PR TITLE
Ignore clang warning

### PR DESCRIPTION
**Pull request by wduminy**
Fix for #2418

### CODE REVIEW

**Comment by Bo98** [comment]
Is this not already fixed in #2232?

**Comment by wduminy** [comment]
> Is this not already fixed in #2232?

We got the error on Sep 24 - so I do not think it was fixed.

> Is this not already fixed in #2232?

This merge was 8 May - I got the error a few days ago.  So I think it was not already fixed.

**Comment by Bo98** [comment]
There hasn't been a release since 2.88 in December of last year. The reporter of #2418 says they are using 2.88.

**Comment by Bo98** [comment]
For those using Homebrew, I backported the patch onto 2.88. As of yesterday, Bullet installs in Homebrew should have the fix.

**Comment by wduminy** [comment]
I had to fix master to get the build to go through on Catalina.  I can check again if you want?

**Comment by Bo98** [comment]
I've not tried master, so feel free, though I don't see anything that would have broken it again.

I took the 2.88 source, applied https://github.com/bulletphysics/bullet3/commit/7638b7c5a659dceb4e580ae87d4d60b00847ef94.patch?full_index=1 and all build bots (High Sierra, Mojave, Catalina) now report success.

**Comment by wduminy** [comment]
Great. Let's drop this MR

**Comment by Bo98** [comment]
For the record, here's my try on master:

```
$ brew install --HEAD bullet
==> Cloning https://github.com/bulletphysics/bullet3.git
Cloning into '/Users/bo/Library/Caches/Homebrew/bullet--git'...
Checking out files: 100% (6991/6991), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> cmake .. [long list of options]
==> make install
==> make clean
==> cmake .. [another long list of options]
==> make install
🍺  /usr/local/Cellar/bullet/HEAD-b25d806_1: 609 files, 16.6MB, built in 1 minute 56 seconds

$ brew test bullet
Testing bullet
==> /usr/bin/clang test.cpp -I/usr/local/Cellar/bullet/HEAD-b25d806_1/include/bullet -L/usr/local/Cellar/bullet/HEAD-b25d806_1/lib -lLinearMath -lc++ -o test
==> ./test
```

**Comment by erwincoumans** [comment]
Time to tag a new release, soon!

**Pull request closed without merging**
