### PR TITLE
Add pybullet.addUserDebugPoints

### PR DESCRIPTION
**Pull request by wkentaro**
https://user-images.githubusercontent.com/4310419/137382677-11c55c8d-ac3a-443a-a5ca-3bc132396397.mp4

https://user-images.githubusercontent.com/4310419/137382681-2adbe48c-87df-499f-a2a9-49c6b0aa5a31.mp4

### CODE REVIEW

**Comment by wkentaro** [comment]
Managed the efficient colored points rendering.

https://user-images.githubusercontent.com/4310419/137589849-3c4607dd-c436-451e-bac6-62856d86b725.mp4

**Comment by erwincoumans** [comment]
One last request, do you have a simple example python script how to use it? You could reply with a zipped attachment (zip files work, other extension often don't).

**Comment by wkentaro** [comment]
Does this work for you? [my_example.zip](https://github.com/bulletphysics/bullet3/files/7533668/my_example.zip)

```
pip install trimesh[easy]
python example_01.py
```

Screen Shot 2021-11-14 at 12 08 09

**Comment by erwincoumans** [comment]
Thanks for the example. Close/re-open to re-trigger CI.

**Comment by erwincoumans** [comment]
LGTM, let's merge the PR. Thanks for the contribution!

**Comment by wkentaro** [comment]
Great! 👍

**Comment by erwincoumans** [comment]
tested with pybullet 3.22 (pip install pybullet) and it works:
Screenshot from 2022-03-25 21-45-29

**Comment by erwincoumans** [comment]
There is a regression in line drawing. Not clear if this is related to this PR, but if so, we may have to revert it until fixed:

image

I will check if reverting this PR fixes it.

**Comment by erwincoumans** [comment]
A minor note: to improve file loading in PyBullet, disable rendering before, and re-enable rendering after loading:
```
p.connect(p.GUI)
p.configureDebugVisualizer(p.COV_ENABLE_RENDERING,0)

root_dir = "YCB_Video_Models"
for i, model_dir in enumerate(os.listdir(root_dir)[:10]):
    model_dir = osp.join(root_dir, model_dir)
    obj_file = osp.join(model_dir, "textured_simple.obj")
    mesh = trimesh.load_mesh(obj_file)
    mesh.apply_translation([i * 0.2 - 1, 0, 0])
    points = mesh.vertices
    colors = mesh.visual.to_color().vertex_colors
    p.addUserDebugPoints(points[:5000], colors[:5000, :3] / 255)

p.configureDebugVisualizer(p.COV_ENABLE_RENDERING,1)
```

**Comment by WhomightIB** [comment]
Yup

**Pull request merged**
